### ISSUE TITLE
Possible to support multiple services?

### ISSUE THREAD

**Issue by HelloGrayson** [Neil-Ni/consul-demo#2]
If I had another service, say `helloworld2` - how difficult would it be to expand on this demo to support that? 

Suppose you wanted `lb:80/helloworld2/*` to be routed to that app...

**Comment by Neil-Ni** [comment]
I briefly demonstrate how to do that near the end of this post: http://blog.neilni.com/2015/09/14/consul-and-consul-template-with-docker-compose/

**Comment by HelloGrayson** [comment]
How would you get the second service configured with nginx simultaneously?

**Comment by Neil-Ni** [comment]
consul-template automatically populates the correct nginx conf for you. do you see anything if you try this? 

```
docker-compose run lb consul-template -consul consul:8500 -template "/etc/consul-templates/app.conf:/tmp/result:service nginx restart" -dry  
```

**Comment by kklepper** [comment]
@Neil-Ni Your question was not for me, but this is what I get:

```
ubuntu@ip-172-31-30-16:~/_registrator/consul-demo$ docker-compose run lb consul-template -consul consul:8500 -template "/etc/consul-templates/app.conf:/tmp/result:service nginx restart" -dry
[fix-attrs.d] applying owners & permissions fixes...
[fix-attrs.d] 00-runscripts: applying...
[fix-attrs.d] 00-runscripts: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2016/04/11 22:41:18 [DEBUG] (config) loading configs from "/etc/consul-template/conf"
2016/04/11 22:41:18 [DEBUG] (config) merging with "/etc/consul-template/conf/app.conf"
Consul Template returned errors:
open /etc/consul-templates/app.conf: no such file or directoryconsul-template exited 14
Received interrupt, cleaning up...
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting
```

My own question is: In my browser I get 

```
504 Gateway Time-out
nginx/1.9.6 
```

In my AWS EC2 Ubuntu t2.micro environment I get the nginx welcome page with `curl localhost` - not exactly hello world, is it? So I really don't understand what is happening here.

```
$ curl localhost:8500/v1/catalog/services
{"consul":[],"consul-53":["udp"],"consul-8400":[],"consul-8500":[],"consuldemo_lb-80":[],"helloworld":["production"]}
```

That is ok. But then what? I read your blog post but cannot reproduce your results. Any hint?

```
helloworld:
  build: ./helloworld
  ports:
    - "3000"
  environment:
    SERVICE_NAME: helloworld
    SERVICE_TAGS: production

consul:
  command: -server -bootstrap
  image: progrium/consul:latest
  ports:
    - "8400:8400"
    - "8500:8500"
    - "8600:53/udp"
    - "172.17.0.1:53:53/udp"                        # docker address

registrator:
  command:  -ip=54.93.106.184  consul://consul:8500 # AWS address
  image: gliderlabs/registrator:latest
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"
  links:
    - consul

lb:
  build: ./lb
  links:
    - consul
  ports:
    - "80:80"
  environment:
    CONSUL_URL: consul:8500
  volumes:
    - ./lb/consul-template:/etc/consul-template
```
